### ISSUE TITLE
App crashes when selecting advanced synchronization settings 

### ISSUE THREAD

**Issue by Ke1i** [phpbg/easysync#40]
**Bug description**
Trying to select individual folders to sync on the webdav server via Synchronization settings > Advanced synchronization settings results in a crash.

**Smartphone:**
 - Device brand/model: HTC/m8
 - Android version: Android 11, LineageOS 18.1 running EasySync 1.11 from Fdroid.

**Comment by samuelchemla** [comment]
Does it crash when toggling enabled/disabled folders ? or when clicking on Advanced synchronization ?
Can you also tell what's your webdav server? nextcloud? apache? other?

**Comment by Ke1i** [comment]
It crashes when I click on the advanced synchronization settings so no I don't even get into the option of selecting folders.
Webdav server is a generic one written in Go and I can connect to it just fine using plain http on a non standard port.
I wanted to use ocis (owncloud) for the server but the self signed cert was a no go.

**Comment by Ke1i** [comment]
Said webdav server:
https://github.com/hacdias/webdav

**Comment by samuelchemla** [comment]
There seems to be something wrong with your dav server.

I published a 1.12 release that prevent the crash and provides more details about the problem.

Please wait a few days so it is available on fdroid (or build it yourself) and report back with the error message.

**Comment by Ke1i** [comment]
Initially I didn't want to sync everything - that's why I wanted to select some specific folders.
Anyway today I created a temporary folder on the server and pointed EasySync to it to sync everything. It worked - with some errors though.
So the webdav server isn't the problem. 
The sync errors I got were some .m4a files failing to copy so maybe you'll want to look into that as well?
Attached are some screengrabs.

![Screenshot_20241011-140849_Easy_Sync](https://github.com/user-attachments/assets/b1aa1d1d-2825-4b47-8b28-648d387ad307)

![Screenshot_20241011-144958_Easy_Sync](https://github.com/user-attachments/assets/8ed17b05-ba98-4982-af73-0ffcd902627c)

![Screenshot_20241011-140535_Easy_Sync](https://github.com/user-attachments/assets/057ff1fc-445a-47b3-b48a-781e1f32d6a5)

![Screenshot_20241011-140626_MiXplorer](https://github.com/user-attachments/assets/a5c09a03-5ea7-4a5a-8249-53287d06db85)

![Screenshot_20241011-140645_Easy_Sync](https://github.com/user-attachments/assets/23f6ba1e-db4b-4a3a-b1a9-59d226b96ed6)

**Comment by Ke1i** [comment]
**Update**
I deleted the music files on the server and manually copied them again from the phone to the server. Synchronization completed successfully without any errors. 
It still crashes though when I go to the advanced synchronization settings. 

![Screenshot_20241011-150634_Easy_Sync](https://github.com/user-attachments/assets/57641543-7c5a-46ef-96e1-fe8ab2fa5292)

**Comment by phpbg** [comment]
Hi, I tried https://github.com/hacdias/webdav and it worked well.

Please wait when 1.12 is released on fdroid and report back.

Easysync does not use WebDav Locks. If you have "message=Locked" errors, check that you don't have other apps accessing your webdav server and locking files...

**Comment by Ke1i** [comment]
Will do.

**Comment by phpbg** [comment]
Hi, 1.12 is there, can you try again?

**Comment by Ke1i** [comment]
Thanks for the heads up.
Version 1.12 doesn't crash when selecting the advanced synchronization settings and it works as expected. 
Thanks for the fix. 
You can close this.
